notarealfile.pdf: 
	pdflatex tr-cse-2015-02.tex
	pdflatex tr-cse-2015-02.tex
	bibtex tr-cse-2015-02
	pdflatex tr-cse-2015-02.tex
	bibtex tr-cse-2015-02
	pdflatex tr-cse-2015-02.tex
	

clean:
	rm -f tr-cse-2015-02.pdf
	rm -f *.dvi
	rm -f *.toc
	rm -f *.bbl
	rm -f *.aux
	rm -f *.log
	rm -f *.blg
	rm -f *.bak
	rm -f *.out
	rm -f *.ps
